var quoteDB = {
    "Oscar Wilde":  ["Be yourself; everyone else is already taken.",
                    "We are all in the gutter, but some of us are looking at the stars.",
                    "Most people are other people. Their thoughts are someone else's opinions, their lives a mimicry, their passions a quotation.",
                    "Man is least himself when he talks in his own person. Give him a mask, and he will tell you the truth.",
                    "Always forgive your enemies; nothing annoys them so much.",
                    "Some cause happiness wherever they go; others whenever they go.",
                    "A cynic is a man who knows the price of everything, and the value of nothing.",
                    "Quotation is a serviceable substitute for wit.",
                    "If you want to tell people the truth, make them laugh, otherwise they’ll kill you.",
                    "It is absurd to divide people into good and bad. People are either charming or tedious.",
                    "No good deed goes unpunished.",
                    "Morality is simply the attitude we adopt towards people we personally dislike.",
                    "It is what you read when you don’t have to that determines what you will be when you can’t help it.",
                    "I don’t want to go to heaven. None of my friends are there.",
                    "A good friend will always stab you in the front.",
                    "Anyone who lives within their means suffers from a lack of imagination.",
                    "I am not young enough to know everything.",
                    "A thing is not necessarily true because a man dies for it.",
                    "Experience is merely the name men gave to their mistakes.",
                    "Man is least himself when he talks in his own person. Give him a mask, and he will tell you the truth.",
                    "The world is a stage and the play is badly cast."],
    "Groucho Marx": ["Whatever it is, I'm against it.",
                    "Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.",
                    "Those are my principles, and if you don't like them... well, I have others.",
                    "One morning I shot an elephant in my pajamas. How he got into my pajamas I'll never know.",
                    "I've had a perfectly wonderful evening. But this wasn't it.",
                    "I never forget a face, but in your case I'll be glad to make an exception.",
                    "Behind every successful man is a woman, behind her is his wife.",
                    "I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.",
                    "From the moment I picked up your book until I put it down, I was convulsed with laughter. Some day I intend reading it.",
                    "Learn from the mistakes of others. You can never live long enough to make them all yourself.",
                    "I never forget a face, but in your case I'll be glad to make an exception.",
                    "Politics is the art of looking for trouble, finding it everywhere, diagnosing it incorrectly and applying the wrong remedies.",
                    "I'm not crazy about reality, but it's still the only place to get a decent meal.",
                    "While money can't buy happiness, it certainly lets you choose your own form of misery.",
                    "I intend to live forever, or die trying.",
                    "Life is a whim of several billion cells to be you for a while.",
                    "Why, look at me. I've worked my way up from nothing to a state of extreme poverty.","I am free of all prejudices. I hate every one equally."],
    "Dave Allen":   ["A good storyteller never lets the facts get in the way.",
                    "I'm an atheist... thank God.",
                    "My church accepts all denominations - fivers, tenners, twenties.",
                    "I don't go out of my way to be outrageous, I just go out of my way to look at things."],
    "Margaret Mead":    ["I was wise enough never to grow up, while fooling people into believing I had.",
                    "Always remember that you are absolutely unique. Just like everyone else.",
                    "It is utterly false and cruelly arbitrary to put all the play and learning into childhood, all the work into middle age, and all the regrets into old age.",
                    "It is easier to change a man's religion than to change his diet.",
                    "Never ever depend on governments or institutions to solve any major problems. All social change comes from the passion of individuals.",
                    "My grandmother wanted me to have an education, so she kept me out of school.",
                    "It is an open question whether any behavior based on fear of eternal punishment can be regarded as ethical or should be regarded as merely cowardly."],
    "Albert Einstein": ["The difference between stupidity and genius is that genius has its limits.",
                    "Common sense is the collection of prejudices acquired by age eighteen.",
                    "The secret to creativity is knowing how to hide your sources.",
                    "The hardest thing in the world to understand is the income tax.",
                    "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
                    "Science is a wonderful thing if one does not have to earn one's living at it.",
                    "If A is a success in life, then A equals X plus Y plus Z. Work is X; Y is play; and Z is keeping your mouth shut."]
}
